### ISSUE TITLE
Console.Key property

### ISSUE THREAD

**Issue by Sonic4080** [popcron/console#6]
In your description you say, that there is a Console.Key property, which can be changed to assing a different opening-key. However in your Code (inside the IsConsoleKey methode) you hardcode the value to BackQuote and Tilde. As a user with a German Keyboard-layout i have neither Key directly on my Keyboard. Therefore i would like to ask you, to implemet the Console.Key property as described in your Readme.

**Comment by Sonic4080** [comment]
Pull Request is made.

**Comment by popcron** [comment]
Merged, thank you
