### ISSUE TITLE
Exposing built-in settings and functionality

### ISSUE THREAD

**Issue by TheDelta** [popcron/console#8]
**Issue:**

On a QWERTY keyboard layout, the console key is actually the "^" caret key.
In Unity, this translates to `KeyCode.Backslash` (numeric: 92)

**Suggestions**

1. Would be cool if this could be automatically recognized which layout is used and then chooses the appropriate default console key.

2. A mention of this in the FAQ could probably resolve some starting issues for ppl with this layout like myself :)

3. `Console.IsConsoleChar` also needs include this keycode. It would be great if this would be a public char array to add/remove chars. 👍

**Comment by popcron** [comment]
Yeah it would probably be better if the keyboard layout, and then check for the appropriate key per layout. I'll take a look at what i can do.

**Comment by popcron** [comment]
Qwerty layout doesnt necessarily dictate where the ~ key is, I too have a qwerty layout keyboard and the key above tab is ~ and not ^ (that one is 6 for my case).

Ukranian keyboard layouts have a § in that place.
Russian keyboards have a Ё.
So on and on...

Detecting keyboard layout with the old input system is platform dependent, using the language enum provided by `Application.systemLanguage` only gives you the locale of the OS, not the layout of the keyboard (someone could have english but have a japanese layout in use). The most I can do is add more checks for different cases like with your keyboard layout.

The new input system (which is handled for) supposedly takes care of keyboard layouts (stated in their documentation), so if the new input system is installed in your project, then '~' will be detected.

So I will add more keys to check for, as well as expose this list of characters to the inspector.

**Comment by TheDelta** [comment]
Thanks for your consideration.
Yeah I also went on that point with Application.systemLanguage or embedding some dll to get the proper keyboard layout and it wasn't worth the effort, so I simply added additional keys.

I moved to the new input system for my own project and noticed there are issues too, due to the KeyCode handling which is used there as well.

My fast workaround to make it work so that the key does trigger the console and `CreateStyle()`:
```
KeyCode m_lastKeyDown = KeyCode.None;
void OnGUI() {
    Event e = Event.current;
    if (!Console.IsOpen && e.type == EventType.KeyDown && e.keyCode != KeyCode.None)
    {
        m_lastKeyDown = e.keyCode;
    }
}

if (m_inputMap.Debug.Console.ReadValue<float>() > 0 && !Console.IsOpen)
{
    if (Console.Key != m_lastKeyDown)
    {
        Console.Key = m_lastKeyDown; // ensure correct key is assigned
    }
}
```
(downside of this is that I have to press the key twice but only on the first time, I can't open the console due to CreateStyle() is bound to Console.Key down event)

There are probably much better solutions but I'm currently messing around with the Input System :D

**Comment by popcron** [comment]
In the `refactor` branch, I have reworked it a bit so that the settings that the console window used to utilized and are now stored in a settings file inside the resources folder. This file defines the colours, gui style, filter and paths to logs.

In addition to that, there is an option to disable the built in checks for opening and closing the console window, which should allow you to manually handle that yourself by toggling `Console.IsOpen`
