### ISSUE TITLE
Expose useful properties

### ISSUE THREAD

**Issue by TheDelta** [popcron/console#9]
**Use case**

- I want to access all lines / text printed to the console to export it into a file but `text` is private
- I want to access the history but `history` is private
- I want to change `Console.HistorySize` but it is private
- I want to change the style, `consoleStyle` and `fpsCounterStyle` are private

**Suggestion**

Expose methods / properties to access and optional modify it.

**Comment by popcron** [comment]
Thank you for the use cases.
Yeah I was thinking of exposing the lines/text, but that is going to be truncated from the beginning at some point, so its better if i'd implement delegates.
The common use case of being able to edit basic things will probably become a setting in the project settings tab, so stay tunned!

**Comment by popcron** [comment]
Closing as im merging this issue with #8
